import 'package:flutter/foundation.dart';
import 'announcement.dart';

class Department {
  final DepartmentTypes type;
  final String url;
  final String startingLink;
  final String titleSelector;
  final String linkSelector;
  final String dateSelector;
  final String dateSelector2;
  final String dateSelector3;

  List<Announcement> announcements = List<Announcement>();

  Department({
    @required this.type,
    @required this.url,
    @required this.startingLink,
    @required this.titleSelector,
    @required this.linkSelector,
    this.dateSelector,
    this.dateSelector2,
    this.dateSelector3,
  });

  static Department getDepartmentInstance(DepartmentTypes type) {
    for (Department d in _departments) if (type == d.type) return d;
    return null;
  }
}

List<Department> _departments = [
  Department(
    type: DepartmentTypes.MuhendislikAnasayfa,
    url: 'https://mf.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://mf.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikBilgisayar,
    url: 'https://bm.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://bm.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikBiyomedikal,
    url: 'https://biomed.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://biomed.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikCevre,
    url: 'https://cevre.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://cevre.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikElektrik,
    url: 'https://em.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://em.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikEndustri,
    url: 'https://endustri.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://endustri.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikEndustriyelTasarim,
    url: 'https://etm.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://etm.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikEnerjiSistemleri,
    url: 'https://esm.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://esm.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikGida,
    url: 'https://gida.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://gida.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikHarita,
    url: 'https://harita.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://harita.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikInsaat,
    url: 'https://insaat.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://insaat.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikMakine,
    url: 'https://me.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://me.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikMalzemeBilimi,
    url: 'https://mbm.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://mbm.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikMekatronik,
    url: 'https://mekatronik.erciyes.edu.tr/?Anasayfa',
    startingLink: 'https://mekatronik.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.MuhendislikTekstil,
    url: 'https://tekstil.erciyes.edu.tr',
    startingLink: 'https://tekstil.erciyes.edu.tr/',
    titleSelector: 'h5.post-title > a.font-13',
    linkSelector: 'h5.post-title > a[href]',
    dateSelector: 'tr > td.font-12',
  ),
  Department(
    type: DepartmentTypes.FakulteDisHekimligi,
    url: 'http://dent.erciyes.edu.tr/Duyuru_Tumu.aspx',
    startingLink: 'http://dent.erciyes.edu.tr/',
    titleSelector: 'div.post-right > h5.mt-0 > a',
    linkSelector: 'div.post-right > h5.mt-0 > a[href]',
    dateSelector: 'li.pr-0 > span',
  ),
  Department(
    type: DepartmentTypes.FakulteEczacilik,
    url: 'https://pharmacy.erciyes.edu.tr',
    startingLink: 'https://pharmacy.erciyes.edu.tr/',
    titleSelector: 'span.aciklama >  a',
    linkSelector: 'span.aciklama >  a[href]',
    dateSelector: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteEdebiyat,
    url: 'https://edebiyat.erciyes.edu.tr/',
    startingLink: 'https://edebiyat.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.EgitimAnasayfa,
    url: 'http://egitim.erciyes.edu.tr',
    startingLink: 'http://egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimEgitimBilimleri,
    url: 'http://egt.egitim.erciyes.edu.tr',
    startingLink: 'http://egt.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimMatematikFenBilimleri,
    url: 'http://matfen.egitim.erciyes.edu.tr',
    startingLink: 'http://matfen.egt.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimTemelEgitim,
    url: 'http://temeg.egitim.erciyes.edu.tr',
    startingLink: 'http://temeg.egt.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimTurkceSosyalBilimler,
    url: 'http://trsos.egitim.erciyes.edu.tr',
    startingLink: 'http://trsos.egt.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimYabanciDiller,
    url: 'http://dil.egitim.erciyes.edu.tr/?id=000026',
    startingLink: 'http://dil.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.EgitimOzelEgitim,
    url: 'http://ozel.egitim.erciyes.edu.tr/?id=000027',
    startingLink: 'http://ozel.egitim.erciyes.edu.tr',
    titleSelector: 'div.news-content-holder > h3 > a > span',
    linkSelector: 'div.news-content-holder > h3 > a[href]',
    dateSelector: 'div.post-date > span',
  ),
  Department(
    type: DepartmentTypes.FakulteFen,
    url: 'http://fen.erciyes.edu.tr',
    startingLink: 'https://fen.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteGuzelSanatlar,
    url: 'http://guzelsanat.erciyes.edu.tr',
    startingLink: 'http://guzelsanat.erciyes.edu.tr/',
    titleSelector: 'div.card-body > h3 > a',
    linkSelector: 'div.card-body > h3 > a[href]',
    dateSelector: 'div.card-head > div.card-stamp > a',
  ),
  Department(
    type: DepartmentTypes.FakulteHavacilik,
    url: 'https://havacilik.erciyes.edu.tr/',
    startingLink: 'https://havacilik.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteHukuk,
    url: 'https://hukuk.erciyes.edu.tr/',
    startingLink: 'https://hukuk.erciyes.edu.tr/', //düzelt
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteIIBF,
    url: 'http://iibf.erciyes.edu.tr',
    startingLink: 'http://iibf.erciyes.edu.tr',
    titleSelector: 'div.Categories > ul > li > a > font',
    linkSelector: 'div.Categories > ul > li > a[href]',
    dateSelector: 'div.Categories > ul > li > span.label',
  ),
  Department(
    type: DepartmentTypes.FakulteIlahiyat,
    url: 'https://ilahiyat.erciyes.edu.tr/',
    startingLink: 'https://ilahiyat.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteIletisim,
    url: 'http://iletisim.erciyes.edu.tr/category/duyuru/',
    startingLink: 'asdfsss',
    titleSelector: 'div.post-info > h2 > a',
    linkSelector: 'div.post-info > h2 > a[href]',
    dateSelector: 'div.post-info > p.postmetadata',
  ),
  Department(
    type: DepartmentTypes.FakulteMimarlik,
    url: 'http://mimarlik.erciyes.edu.tr',
    startingLink: 'http://mimarlik.erciyes.edu.tr',
    titleSelector: 'div.duyurugenislik2 > a',
    linkSelector: 'div.duyurugenislik2 > a[href]',
    dateSelector: 'div > div[style|=font]',
    dateSelector2: 'div > div[style|=margin]',
  ),
  Department(
    type: DepartmentTypes.FakulteSaglikBilimleri,
    url: 'https://sbf.erciyes.edu.tr/',
    startingLink: 'https://sbf.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteSeyraniZiraat,
    url: 'https://ziraat.erciyes.edu.tr/',
    startingLink: 'https://ziraat.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteSporBilimleri,
    url: 'https://spbf.erciyes.edu.tr/',
    startingLink: 'https://spbf.erciyes.edu.tr/',
    titleSelector: 'li > span.aciklama > a',
    linkSelector: 'li > span.aciklama > a[href]',
    dateSelector: 'li > span.img > span.gun',
    dateSelector2: 'li > span.img > span.ay',
    dateSelector3: 'li > span.img > span.yil',
  ),
  Department(
    type: DepartmentTypes.FakulteTip,
    url: 'http://tip.erciyes.edu.tr/bizden-duyurular.html',
    startingLink: 'http://tip.erciyes.edu.tr/',
    titleSelector: 'div.irs-courses-content > h4 > a',
    linkSelector: 'div.irs-courses-content > h4 > a[href]',
    dateSelector: 'li > p > a',
  ),
  Department(
    type: DepartmentTypes.FakulteTurizm,
    url: 'http://turizm.erciyes.edu.tr/duyurulist.asp',
    startingLink: 'http://turizm.erciyes.edu.tr/',
    titleSelector: 'div.duyurukutu > a',
    linkSelector: 'div.duyurukutu > a[href]',
    dateSelector: 'div.duyurukutu > div.duyurutarih',
  ),
  Department(
    type: DepartmentTypes.FakulteVeteriner,
    url: 'https://veteriner.erciyes.edu.tr',
    startingLink: 'https://veteriner.erciyes.edu.tr/',
    titleSelector: 'div.profile-post-in > h3.heading-xs > a',
    linkSelector: 'div.profile-post-in > h3.heading-xs > a[href]',
    dateSelector: 'div.profile-post > span.profile-post-numb',
  ),
  Department(
    type: DepartmentTypes.Erasmus,
    url: 'https://erasmus.erciyes.edu.tr/duyurular.asp',
    startingLink: 'https://erasmus.erciyes.edu.tr/',
    titleSelector: 'a.link1',
    linkSelector: 'div > a[href]',
    dateSelector: 'div.cufonbaslik_ic1 > abbr > i',
  ),
  Department(
    type: DepartmentTypes.Obisis,
    url: 'https://obisis.erciyes.edu.tr',
    startingLink: '',
    titleSelector: 'tr > td > span.NormalBlue',
    linkSelector: 'tr > td > span.NormalBlue',
  ),
  /* Department(
    type: DepartmentTypes.Erasmus,
    url: '',
    startingLink: '',
    titleSelector: '',
    linkSelector: '',
    dateSelector: '',
  ), */
];

enum DepartmentTypes {
  MuhendislikAnasayfa,
  MuhendislikBilgisayar,
  MuhendislikBiyomedikal,
  MuhendislikCevre,
  MuhendislikElektrik,
  MuhendislikEndustri,
  MuhendislikEndustriyelTasarim,
  MuhendislikEnerjiSistemleri,
  MuhendislikGida,
  MuhendislikHarita,
  MuhendislikInsaat,
  MuhendislikMakine,
  MuhendislikMalzemeBilimi,
  MuhendislikMekatronik,
  MuhendislikTekstil,
  FakulteDisHekimligi,
  FakulteEczacilik,
  FakulteEdebiyat,
  FakulteFen,
  FakulteGuzelSanatlar,
  FakulteHavacilik,
  FakulteHukuk,
  FakulteIIBF,
  FakulteIlahiyat,
  FakulteIletisim,
  FakulteMimarlik,
  FakulteSaglikBilimleri,
  FakulteSeyraniZiraat,
  FakulteSporBilimleri,
  FakulteTip,
  FakulteTurizm,
  FakulteVeteriner,
  EgitimAnasayfa,
  EgitimEgitimBilimleri,
  EgitimMatematikFenBilimleri,
  EgitimTemelEgitim,
  EgitimTurkceSosyalBilimler,
  EgitimYabanciDiller,
  EgitimOzelEgitim,
  MeslekYuksekOkulAdalet,
  MeslekYuksekOkulHalilBayraktarSaglikHizmetleri,
  YuksekOkulYabanciDil,
  EnstituAtaturkIlkeleriVeInkiplaplari,
  EnstituEgitimBilimleri,
  EnstituFenBilimleri,
  EnstituGevherNesibeGenomVeKokHucre,
  EnstituGuzelSanatlar,
  EnstituSaglikBilimleri,
  EnstituSosyalBilimler,
  Obisis,
  Erasmus,
}
